import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        status: {
          // Soft Blues
          "powder-blue": "hsl(var(--status-powder-blue))",
          "powder-blue-foreground": "hsl(var(--status-powder-blue-foreground))",
          "sky-blue": "hsl(var(--status-sky-blue))",
          "sky-blue-foreground": "hsl(var(--status-sky-blue-foreground))",
          periwinkle: "hsl(var(--status-periwinkle))",
          "periwinkle-foreground": "hsl(var(--status-periwinkle-foreground))",
          "ice-blue": "hsl(var(--status-ice-blue))",
          "ice-blue-foreground": "hsl(var(--status-ice-blue-foreground))",
          // Soft Greens
          mint: "hsl(var(--status-mint))",
          "mint-foreground": "hsl(var(--status-mint-foreground))",
          sage: "hsl(var(--status-sage))",
          "sage-foreground": "hsl(var(--status-sage-foreground))",
          seafoam: "hsl(var(--status-seafoam))",
          "seafoam-foreground": "hsl(var(--status-seafoam-foreground))",
          pistachio: "hsl(var(--status-pistachio))",
          "pistachio-foreground": "hsl(var(--status-pistachio-foreground))",
          // Soft Yellows/Oranges
          cream: "hsl(var(--status-cream))",
          "cream-foreground": "hsl(var(--status-cream-foreground))",
          peach: "hsl(var(--status-peach))",
          "peach-foreground": "hsl(var(--status-peach-foreground))",
          apricot: "hsl(var(--status-apricot))",
          "apricot-foreground": "hsl(var(--status-apricot-foreground))",
          buttercup: "hsl(var(--status-buttercup))",
          "buttercup-foreground": "hsl(var(--status-buttercup-foreground))",
          // Soft Pinks/Roses
          blush: "hsl(var(--status-blush))",
          "blush-foreground": "hsl(var(--status-blush-foreground))",
          rose: "hsl(var(--status-rose))",
          "rose-foreground": "hsl(var(--status-rose-foreground))",
          coral: "hsl(var(--status-coral))",
          "coral-foreground": "hsl(var(--status-coral-foreground))",
          mauve: "hsl(var(--status-mauve))",
          "mauve-foreground": "hsl(var(--status-mauve-foreground))",
          // Soft Purples
          lavender: "hsl(var(--status-lavender))",
          "lavender-foreground": "hsl(var(--status-lavender-foreground))",
          lilac: "hsl(var(--status-lilac))",
          "lilac-foreground": "hsl(var(--status-lilac-foreground))",
          "periwinkle-purple": "hsl(var(--status-periwinkle-purple))",
          "periwinkle-purple-foreground": "hsl(var(--status-periwinkle-purple-foreground))",
          // Soft Grays
          pearl: "hsl(var(--status-pearl))",
          "pearl-foreground": "hsl(var(--status-pearl-foreground))",
        },
        urgency: {
          "1": "hsl(var(--urgency-1))",
          "1-foreground": "hsl(var(--urgency-1-foreground))",
          "2": "hsl(var(--urgency-2))",
          "2-foreground": "hsl(var(--urgency-2-foreground))",
          "3": "hsl(var(--urgency-3))",
          "3-foreground": "hsl(var(--urgency-3-foreground))",
          "4": "hsl(var(--urgency-4))",
          "4-foreground": "hsl(var(--urgency-4-foreground))",
          "5": "hsl(var(--urgency-5))",
          "5-foreground": "hsl(var(--urgency-5-foreground))",
          "6": "hsl(var(--urgency-6))",
          "6-foreground": "hsl(var(--urgency-6-foreground))",
          "7": "hsl(var(--urgency-7))",
          "7-foreground": "hsl(var(--urgency-7-foreground))",
          "8": "hsl(var(--urgency-8))",
          "8-foreground": "hsl(var(--urgency-8-foreground))",
          "9": "hsl(var(--urgency-9))",
          "9-foreground": "hsl(var(--urgency-9-foreground))",
          "10": "hsl(var(--urgency-10))",
          "10-foreground": "hsl(var(--urgency-10-foreground))",
          "11": "hsl(var(--urgency-11))",
          "11-foreground": "hsl(var(--urgency-11-foreground))",
          "12": "hsl(var(--urgency-12))",
          "12-foreground": "hsl(var(--urgency-12-foreground))",
          "13": "hsl(var(--urgency-13))",
          "13-foreground": "hsl(var(--urgency-13-foreground))",
          "14": "hsl(var(--urgency-14))",
          "14-foreground": "hsl(var(--urgency-14-foreground))",
          "15": "hsl(var(--urgency-15))",
          "15-foreground": "hsl(var(--urgency-15-foreground))",
          "16": "hsl(var(--urgency-16))",
          "16-foreground": "hsl(var(--urgency-16-foreground))",
          "17": "hsl(var(--urgency-17))",
          "17-foreground": "hsl(var(--urgency-17-foreground))",
          "18": "hsl(var(--urgency-18))",
          "18-foreground": "hsl(var(--urgency-18-foreground))",
          "19": "hsl(var(--urgency-19))",
          "19-foreground": "hsl(var(--urgency-19-foreground))",
          "20": "hsl(var(--urgency-20))",
          "20-foreground": "hsl(var(--urgency-20-foreground))",
        },
        notification: {
          info: "hsl(var(--notification-info))",
          success: "hsl(var(--notification-success))",
          warning: "hsl(var(--notification-warning))",
          error: "hsl(var(--notification-error))",
        },
        star: "hsl(var(--star))",
        role: {
          owner: "hsl(var(--role-owner))",
          "owner-foreground": "hsl(var(--role-owner-foreground))",
          manager: "hsl(var(--role-manager))",
          "manager-foreground": "hsl(var(--role-manager-foreground))",
          member: "hsl(var(--role-member))",
          "member-foreground": "hsl(var(--role-member-foreground))",
        },
        section: {
          essentials: "hsl(var(--section-essentials))",
          "essentials-bg": "hsl(var(--section-essentials-bg))",
          assignment: "hsl(var(--section-assignment))",
          "assignment-bg": "hsl(var(--section-assignment-bg))",
          priority: "hsl(var(--section-priority))",
          "priority-bg": "hsl(var(--section-priority-bg))",
          references: "hsl(var(--section-references))",
          "references-bg": "hsl(var(--section-references-bg))",
          context: "hsl(var(--section-context))",
          "context-bg": "hsl(var(--section-context-bg))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-in-up": "fade-in-up 0.5s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "bounce-subtle": "bounce-subtle 0.6s ease-out",
        "pulse-subtle": "pulse-subtle 2s ease-in-out infinite",
        "count-up": "count-up 0.8s ease-out",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(-10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
        "count-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
