-- Nuclear option: Dynamically find and drop constraints that are NOT the correct pair constraint
DO $$
DECLARE r RECORD;
BEGIN -- Iterate over all unique constraints on public.team_mappings
FOR r IN (
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.team_mappings'::regclass
        AND contype = 'u'
) LOOP -- If the constraint is NOT the one we want to keep (team_mapping_pair_unique)
-- We drop it. This covers 'team_member_unique' and any potential autogenerated names.
IF r.conname != 'team_mapping_pair_unique' THEN EXECUTE 'ALTER TABLE public.team_mappings DROP CONSTRAINT ' || quote_ident(r.conname);
END IF;
END LOOP;
END $$;
-- Ensure the correct constraint exists
do $$ begin if not exists (
    select 1
    from pg_constraint
    where conname = 'team_mapping_pair_unique'
) then
alter table public.team_mappings
add constraint team_mapping_pair_unique unique (pm_id, team_member_id);
end if;
end $$;